services:
  api:
    build: .
    env_file:
      - .env
    environment:
      - TEST_MONGODB_URI=mongodb://mongo:27017/t1db_test
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./app:/app/app:rw
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "localhost/test", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mongo-data:
